name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ heroku-deploy ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

      - name: Run tests
        run: php artisan test --stop-on-failure
